-- Create chatbot_questions table
CREATE TABLE IF NOT EXISTS chatbot_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    category TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE chatbot_questions ENABLE ROW LEVEL SECURITY;

-- Create policy for all access (simplified for now, following project pattern)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'chatbot_questions' AND policyname = 'Allow all access to chatbot_questions'
    ) THEN
        CREATE POLICY "Allow all access to chatbot_questions" ON chatbot_questions FOR ALL USING (true);
    END IF;
END $$;

-- Add manage_chatbot permission
INSERT INTO permissions (name, description)
SELECT 'manage_chatbot', 'Can manage chatbot instructions and question list'
WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE name = 'manage_chatbot');

-- Assign manage_chatbot permission to admin role if not already assigned
INSERT INTO role_permissions (role, permission_id)
SELECT 'admin', id FROM permissions WHERE name = 'manage_chatbot'
ON CONFLICT DO NOTHING;

-- Also assign to manager role if needed (optional, but typical for this app)
INSERT INTO role_permissions (role, permission_id)
SELECT 'manager', id FROM permissions WHERE name = 'manage_chatbot'
ON CONFLICT DO NOTHING;
