import { processCsv, mergeRecords } from './processor.js';
import { upsertCptCodes } from './db.js';
import { downloadLatestFullPack } from './download.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DATA_DIR = path.join(__dirname, 'asc_aa');

async function main() {
    const mode = process.argv[2]; // 'seed' or 'update'

    console.log(`🚀 Starting CPT Service in [${mode || 'default'}] mode`);

    try {
        if (mode === 'seed') {
            await runSeed();
        } else {
            await runUpdate(); // Default is update (check for new files)
        }
    } catch (error) {
        console.error("🔥 Fatal Error:", error);
        process.exit(1);
    }
}

async function runSeed() {
    const seedDir = path.join(DATA_DIR, 'seed');
    if (!fs.existsSync(seedDir)) {
        console.log(`⚠️  Seed directory not found at ${seedDir}`);
        console.log("   Please place the 4 quarterly CSVs there to seed, or run 'update' to fetch latest.");
        fs.mkdirSync(seedDir, { recursive: true });
        return;
    }

    const files = fs.readdirSync(seedDir).filter(f => f.endsWith('.csv'));
    if (files.length === 0) {
        console.log("ℹ️  No CSV files found in seed directory.");
        return;
    }

    files.sort();

    const allRecordSets = [];
    for (const file of files) {
        console.log(`📖 Reading seed file: ${file}`);
        const records = await processCsv(path.join(seedDir, file));
        allRecordSets.push(records);
    }

    console.log("🔄 Merging records (keeping latest)...");
    const mergedRecords = mergeRecords(allRecordSets);

    console.log(`💾 Upserting ${mergedRecords.length} unique records to Supabase...`);
    const result = await upsertCptCodes(mergedRecords);

    const report = {
        type: 'SEED',
        timestamp: new Date().toISOString(),
        files_processed: files,
        total_records_found: mergedRecords.length,
        records_upserted: result.count,
        status: result.error ? 'FAILED' : 'SUCCESS',
        error: result.error
    };

    await generateReport(report);
    console.log("✅ Seeding Complete!");
}

async function runUpdate() {
    console.log("🌐 Checking CMS for updates...");
    let csvPath;
    try {
        csvPath = await downloadLatestFullPack(DATA_DIR);
    } catch (error) {
        console.error("Failed to download update:", error);
        await generateReport({ type: 'UPDATE', status: 'FAILED', error: error.message });
        throw error;
    }

    if (!csvPath) {
        console.log("No file downloaded.");
        return;
    }

    console.log(`PARSING: ${csvPath}`);
    const records = await processCsv(csvPath);

    console.log(`💾 Upserting ${records.length} records...`);
    const result = await upsertCptCodes(records);

    const report = {
        type: 'UPDATE',
        timestamp: new Date().toISOString(),
        downloaded_file: path.basename(csvPath),
        total_records_found: records.length,
        records_upserted: result.count,
        status: result.error ? 'FAILED' : 'SUCCESS',
        error: result.error
    };

    await generateReport(report);

    console.log("✅ Update Complete.");
    console.log(`   File: ${path.basename(csvPath)}`);
    console.log(`   Records: ${result.count}`);
}

async function generateReport(data) {
    const reportDir = path.join(__dirname, 'reports');
    if (!fs.existsSync(reportDir)) fs.mkdirSync(reportDir, { recursive: true });

    const filename = `report-${data.type.toLowerCase()}-${new Date().toISOString().replace(/[:.]/g, '-')}.md`;
    const filePath = path.join(reportDir, filename);

    const content = `
# ASC CPT Code Auto-Update Report
**Date:** ${new Date().toLocaleString()}
**Type:** ${data.type}
**Status:** ${data.status}

## Summary
- **Files Processed:** ${data.files_processed ? data.files_processed.join(', ') : data.downloaded_file}
- **Total Records Found:** ${data.total_records_found}
- **Records Upserted to DB:** ${data.records_upserted}

${data.error ? `## ❌ Errors\n\`\`\`json\n${JSON.stringify(data.error, null, 2)}\n\`\`\`` : ''}

---
*Generated by Antigravity CPT Seeder Service*
`;

    fs.writeFileSync(filePath, content);
    console.log(`📝 Report generated: ${filePath}`);
}

main();
